/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'itmuser' at '06/07/16 12:26' with Gradle 2.14
 *
 * @author itmuser, @date 06/07/16 12:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
